### ISSUE TITLE
Sign Up Load Error

### ISSUE THREAD

**Issue by swire** [PayPal-Mobile/ios-here-sdk-dist#46] opened 2015-08-20 09:19 UTC
We're done with our integration except for one final piece. We are getting this 'Load Error' — see bottom of picture where the status updates to 'Load Error' once you tap 'Sign Up'...

We've built a PhoneGap plugin and sync and all transaction features are working, except for this.

We want the user to:
- tap 'Sign Up' and to complete the sign up flow within our app, 
- then be dropped off to the new user welcome and tour.

Also, Alex from our team says the Sign Up requires them to go to email to confirm and then come back. Is that correct? Or, can the Sign Up option be completed fully in app? It breaks the user sign up flow into the app if we direct them outside of the app to complete another step.

@BCGood and @AlexGamezo - please add any additional and helpful info.

![img_4648](https://cloud.githubusercontent.com/assets/12964237/9379857/0736398e-46e1-11e5-8efc-817569df35d4.PNG)

**Comment by ppmtscory** [comment] 2015-08-20 19:25
Unfortunately the onboarding piece doesn't have a native flow.  Are you doing this inside of a webview?  Is there any extra information about what the 'error' actually is?  Anything in the console logs?   As for email, yes, if user's are signing up for PayPal, then they will receive an email with a link to confirm their email address.  The onboarding flow will complete, but they will need to confirm their email address before they are able to transact.

**Comment by bcgood** [comment] 2015-08-20 20:06
No error, I opened the sign up link to https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_registration-run on a desktop and it works fine. I'm digging more into it and it seems to be a bug relating to phonegap inapp browser when trying to open the link.

**Comment by ppmtscory** [comment] 2015-08-20 20:17
Thanks for the update @bcgood, please keep us posted.

**Comment by djMax** [comment] 2015-08-20 21:29
I doubt the flow can be completed in app, as the point of the email is essentially a second auth factor. I suppose you could access their email to try and fetch the confirmation code, but that sounds like more trouble than it's worth.

**Comment by swire** [comment] 2015-08-20 22:00
@djMax the email doesn't have to be confirmed during the onboarding - we can simply provide an alert before making a transaction in our app that they'll have to confirm via email before making a transaction. 

Thus, we're simply stuck on the in-app browser for PhoneGap not working, providing the 'load error' when the 'Sign Up' text link is tapped.

@ppmtscory 
PhoneGap boards and support are turning up no answers on this. Now, we're stuck and further delaying our push based on this one final bug. Not sure what else to do other than not allow a Sign Up in app and leave a broken link there. That doesn't sound like a good solution at all.

**Comment by swire** [comment] 2015-08-20 22:22
@ppmtscory also, if you try other text links in the in-app browswer, they do work, which is strange. It's only the 'Sign Up' link. We don't know what is different about the 'Sign Up' link so I'm not sure we can do anything about it. I think it's on your end.

**Comment by djMax** [comment] 2015-08-20 23:19
Do you have any sort of logs of the HTTP requests the browser is trying to make (and their results?)?

**Comment by djMax** [comment] 2015-08-20 23:20
Any way for us to get the app to reproduce it here @ paypal?

**Comment by swire** [comment] 2015-08-20 23:25
@djMax - I'm asking @bcgood to reply to you on this. He'll get back to you in a few minutes.

**Comment by djMax** [comment] 2015-08-20 23:27
If you need to send me email it's just my first initial and then last name @ paypal.com

**Comment by bcgood** [comment] 2015-08-20 23:50
@djMax I'm unable to grab the HTTP requests from the inapp browser. A way to reproduce it would be to open the url which starts the sync process from PayPal Here in the inapp browser of a Cordova PhoneGap app and then clicking on Sign Up.

**Comment by swire** [comment] 2015-08-21 00:29
@djMax - Brian's solution to test should be simple with a sample app (any sample cordova phonegap app). Or, we can get you access but that will take longer. Let us know.

**Comment by ppmtscory** [comment] 2015-08-21 00:39
I think I may see something here... give me a couple minutes to examine...

**Comment by ppmtscory** [comment] 2015-08-21 00:44
@bcgood or @swire can you please try https://www.sandbox.paypal.com/signup/account in the in-app browser and let me know if that will work?

**Comment by bcgood** [comment] 2015-08-21 00:45
@ppmtscory Let me give it try and I'll get back

**Comment by bcgood** [comment] 2015-08-21 00:51
@ppmtscory yes it works fine

**Comment by ppmtscory** [comment] 2015-08-21 00:56
Ok, thank you.  So with the sandbox URL, there's a bad redirect on our end that seems to be causing your frustrations.  I will follow up with our onboarding team to have this corrected.  Good news is that it won't require any extra integration work on your end when it's fixed.  Even better news is that it's only happening on sandbox and Live is fine.  If you'd like to test Live, the URL is https://www.paypal.com/us/cgi-bin/webscr?cmd=_registration-run (just minus the 'sandbox').

**Comment by swire** [comment] 2015-08-21 01:08
That is really great news @ppmtscory - do you expect it to be fixed by tomorrow morning perhaps or longer? We would love to test it before pushing this update to Apple tomorrow. We are so many weeks behind schedule now we really need to push tomorrow. We're a little nervous to just trust it will work when Live as if it doesn't we'll be setback at least two more weeks due to the app review wait times and having to resubmit.

**Comment by ppmtscory** [comment] 2015-08-21 01:12
@swire you are going to submit to Apple using the Sandbox endpoints?

**Comment by ppmtscory** [comment] 2015-08-21 01:20
I have sent the issue off to the right folks to correct it.  Unfortunately I can't give you a guarantee on it being fixed tomorrow morning.  They'll most likely need to wait for the next release window.  I'm not certain when that is right now but I can definitely update you back here when it's fixed.  I pasted the Live URL up above if you want to test that out in the in-app browser.  It redirects fine for me to the same 'Live' version of the URL that @bcgood tested and said worked.

**Comment by swire** [comment] 2015-08-21 01:30
Thank you. We have to push tomorrow so we'll cross our fingers and hope for the best. We'll test the live one now.

---
Zack Swire
eGood.com/Zack

626-641-9198
zack@egood.com

**Comment by bcgood** [comment] 2015-08-21 02:03
@ppmtscory I've just tested with a live url and the sign up link does work. I'm however unable to test the flow to see if I actually get an OAuth code back that I can exchange for an OAuth token because my application keeps getting rejected in the end. Is there anyway around I can test that or is the only way to just wait until PayPal resolves this issue?

**Comment by ppmtscory** [comment] 2015-08-21 02:10
Are you talking about an application after that signup link?  The application for PPH should take place before that page even happens.  If you're directing customers to this page directly, then that should be if they already have an account, have been approved for PPH, and this flow is to grant the permissions to you to process on their behalf.  Let me reach out to you on email and get some more info about your integration.

**Comment by ppmtscory** [comment] 2015-08-21 17:30
Per our phone conversation, I'm going to go ahead and close this issue out.  If anything else is needed, please don't hesitate to let us know.

**Closed by ppmtscory** 2015-08-21 17:30 UTC
Labels: bug
