### ISSUE TITLE
SDKSampleApp unable read swipe

### ISSUE THREAD

**Issue by um-developer** [PayPal-Mobile/ios-here-sdk-dist#43] opened 2015-08-14 14:45 UTC
Hi,

I am trying to run the SDKSampleApp, but it is unable to read card swipes. The interesting part is it is not even asking for microphone access. Is there a change in project settings that need to be done so it can get microphone access?

Thanks,
~D

**Comment by ppmtscory** [comment] 2015-08-14 16:01
There shouldn't be anything extra that needs to be done to the project.  Is there anything that shows up in the console log as far as the reader being detected?  Also, can you validate that you are not using the NOHW version of the sample app?  I'm not seeing the same issue, so if you can provide any information about your device/testing/etc to help me reproduce, that would be great.

**Comment by um-developer** [comment] 2015-08-14 19:01
Thanks for quick reply. This is what i am getting in the logs. I have testing this using iPad running iOS 9, iPhone running iOS 8.4

I see it is having trouble connecting to a config server?

Error: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo=0x6214a0 {NSErrorFailingURLStringKey=https://pph-mobileconfig.ebaystratus.com/ios-sdk-features-1.2.json, _kCFStreamErrorCodeKey=61, NSErrorFailingURLKey=https://pph-mobileconfig.ebaystratus.com/ios-sdk-features-1.2.json, NSLocalizedDescription=Could not connect to the server., _kCFStreamErrorDomainKey=1, NSUnderlyingError=0x748790 "Could not connect to the server."}


Could that be causing it?

**Comment by ppmtscory** [comment] 2015-08-14 19:31
No, that shouldn't be the culprit.  I see the same thing in my logs, from an older config server.  When I get in, I click Simple Transaction > Purchase > Credit Card: Swipe.  When I plug in the swiper after the app opens, that shows me the volume alert box and, if I hadn't loaded the app yet before, the alert to allow access to the microphone.  On the screen to swipe, it shows me messages of reader detection and the readiness to accept swipe data.

If you don't see the option for microphone, perhaps just go into your settings on your phone, into the privacy section, click microphone, and then grant access to the SDKSampleApp.

**Comment by um-developer** [comment] 2015-08-15 00:04
That is the trouble i am having. The SDKSampleApp does not even list in the privacy->microphone section. It is as if the SDK is not even trying to access it? Any other idea?

**Comment by ppmtscory** [comment] 2015-08-17 15:12
Is your volume turned all the way up on your device?  Are you sure you're not using the NOHW version of the Sample App?

**Comment by jaredegan** [comment] 2015-08-17 15:50
If it's not showing up in the privacy section of the Settings app, then the line of code asking for permission is just never running. The failing json could be the issue if the SDK uses that to decide to listen.

Cory, can you delete the sample app and reinstall it to try and reproduce? The featuremap could be cached for you, so the missing json file wouldn't necessarily be an issue.

I've raised this issue to some more people at PayPal, so it should get some more attention soon.

**Comment by jaredegan** [comment] 2015-08-17 15:54
FYI, Just talked to another dev and he says the JSON file shouldn't been an issue, since the SDK ships with a cached version.

**Comment by um-developer** [comment] 2015-08-17 16:25
I don't see a NOHW version of the app. I only see one version of the application. How do i know if it is NOHW?

~Um

**Comment by ppmtscory** [comment] 2015-08-18 13:43
In the SDKSampleApp folder, the first Xcode project listed is the NOHWSampleApp.xcodeproj.  This one is the NOHW Sample App which means it doesn't have any of the hardware libraries included.  This version would be for developers that are already using a Magtek library and want to control all of the swiper functionality on their own.

**Comment by um-developer** [comment] 2015-08-18 22:45
I have confirmed that I am not using NOHWSampleApp. Any other idea as to what is going on?

~Um

**Comment by ppmtscory** [comment] 2015-08-19 16:27
Are you modifying any code within the Sample App?  Anything that would conflict with the permissions?  This is difficult since I'm not able to reproduce with the same scenario.

**Comment by um-developer** [comment] 2015-08-24 01:41
I haven't made any changes to the code, can you please confirm what version of Xcode you are using and what iOS version are you testing on? Also are you testing on iPhone or iPad?

~Um

**Comment by ronaldsmartin** [comment] 2015-09-11 00:41
Hi @ppmtscory,

Has this been resolved yet? I am also running into the same issue on my iPad Air 2 (iOS 8.4.1, Xcode 6.4). Can confirm that this is `SDKSampleApp.xcodeproj` and not `NOHWSampleApp`.

Here's the logs after navigating to the **Credit Card: Swipe** screen:

```
2015-09-10 17:30:33.702 SDKSampleApp[7094:2057388] Debug: PayPalHere:  :setIgnoreHardwareReaders state: Allow
2015-09-10 17:30:33.703 SDKSampleApp[7094:2057388] Debug: PayPalHere: beginPaymentWithAmount entry
2015-09-10 17:30:33.703 SDKSampleApp[7094:2057388] PayPalHere: Clearing payment data
2015-09-10 17:30:33.704 SDKSampleApp[7094:2057388] Debug: PayPalHere: setState: 1
2015-09-10 17:30:33.705 SDKSampleApp[7094:2057388] Debug: PayPalHere: setState: !_ignoreHardwareReaders
2015-09-10 17:30:33.705 SDKSampleApp[7094:2057388] Debug: PayPalHere: setState: listenForCardData:YES
2015-09-10 17:30:33.706 SDKSampleApp[7094:2057388] Debug: PayPalHere: listen for Card Data but should we listen? : YES and more importantly, is monitoring enabled? :YES
2015-09-10 17:30:33.706 SDKSampleApp[7094:2057388] Debug: PayPalHere: listenForCardData:  activateReader
2015-09-10 17:30:33.707 SDKSampleApp[7094:2057388] Debug: PayPalHere: CardReaderManager::activateReader
2015-09-10 17:30:34.138 SDKSampleApp[7094:2057406] 00:30:33.0702      Main thread | PayPalHere:  :setIgnoreHardwareReaders state: Allow
2015-09-10 17:30:34.138 SDKSampleApp[7094:2057406] 00:30:33.0703      Main thread | PayPalHere: beginPaymentWithAmount entry
2015-09-10 17:30:34.139 SDKSampleApp[7094:2057406] 00:30:33.0703      Main thread | PayPalHere: Clearing payment data
2015-09-10 17:30:34.139 SDKSampleApp[7094:2057406] 00:30:33.0705      Main thread | PayPalHere: setState: 1
2015-09-10 17:30:34.139 SDKSampleApp[7094:2057406] 00:30:33.0705      Main thread | PayPalHere: setState: !_ignoreHardwareReaders
2015-09-10 17:30:34.139 SDKSampleApp[7094:2057406] 00:30:33.0705      Main thread | PayPalHere: setState: listenForCardData:YES
2015-09-10 17:30:34.140 SDKSampleApp[7094:2057406] 00:30:33.0706      Main thread | PayPalHere: listen for Card Data but should we listen? : YES and more importantly, is monitoring enabled? :YES
2015-09-10 17:30:34.140 SDKSampleApp[7094:2057406] 00:30:33.0707      Main thread | PayPalHere: listenForCardData:  activateReader
2015-09-10 17:30:34.140 SDKSampleApp[7094:2057406] 00:30:33.0707      Main thread | PayPalHere: CardReaderManager::activateReader
```

but like @um-developer, I received no prompt to access the microphone, and thus there's no entry yet in my Privacy Settings.

**Comment by djMax** [comment] 2015-09-11 02:30
Can you try manually asking for microphone permission before initializing the SDK merchant? Here is a code snippet:
```
- (void)checkMicrophone {
    if ([[AVAudioSession sharedInstance] respondsToSelector:@selector(requestRecordPermission:)]) {
        [[AVAudioSession sharedInstance] performSelector:@selector(requestRecordPermission:) withObject:(id)^(BOOL granted) {
            dispatch_async(dispatch_get_main_queue(), ^(void) {
                NSLog(@"Microphone permissions granted? %@", (granted) ? @"YES" : @"NO");
                if (!granted) {
                    // Tell the user to go to Settings  >  Privacy  >  Microphone and give us permission.
                } else {
                    // You're good to go.
                }
            });
        }];
    } else {
        // You're good to go.
    }
}
```

**Comment by ronaldsmartin** [comment] 2015-09-11 17:00
@djMax: Thanks, that at least got the microphone permission set.

However, I still can't get Simple Transaction > Credit Card: Swipe to work. After setting some breakpoints in `STCardSwipeViewController`, it doesn't look like `PPHTransactionManagerDelegate`'s `onPaymentEvent:` method is being called for most events. I haven't narrowed down the exact path, but sometimes when I hit **Back** after swiping the card, `onPaymentEvent:` gets called with `event.eventType == ePPHTransactionType_Idle`.

Any advice on how to proceed? Thanks again!

**Comment by um-developer** [comment] 2015-09-14 07:17
Any updates on this? I would love to integrate the reader in my app

~Um

**Comment by ppmtscory** [comment] 2015-09-14 14:38
@um-developer @ronaldsmartin I think I'm seeing something here but would like you to confirm the same.  When you open the Sample App, click 'Custom Card Reader Controls' > 'Settings', and let me know what it says for the SDK Version.

**Comment by ronaldsmartin** [comment] 2015-09-14 16:30
@ppmtscory:

I see the following:

* SDK Version: **1.5.2.nhw**
* Sample App Version: **1001**
* Merchant Checkin Status: **[off]**
* Tax Rate: **.10**
* Payment Flow Type: **Full Capture**

**Comment by ppmtscory** [comment] 2015-09-14 16:36
Ah, ok, thank you for the confirmation.  It looks like the Sample App may be reading from the 'no hardware' version of the SDK.  I've escalated this internally to have somebody with access check and, if that's the case, make the change.  I'll keep you updated here.

**Comment by ppmtscory** [comment] 2015-09-14 16:46
Yes, it seems that's the case.  Please use the [1.5.1 version](https://github.com/PayPal-Mobile/ios-here-sdk-dist/tree/13e4a1cb741a10acee9a1072fc781c9deb9c5778) instead and let me know if you still have issues.

**Comment by ronaldsmartin** [comment] 2015-09-14 17:05
Thanks! I'll try this and let you know how it goes.

**Comment by ronaldsmartin** [comment] 2015-09-14 17:48
Hi @ppmtscory,

I rolled back to the tag you specified, but still have the same issue.

It looks like the SDK Version is still **1.5.2.nhw**.

**Comment by ppmtscory** [comment] 2015-09-14 18:14
Are you sure you are running that particular version of the sample app?  I just went to that tree, downloaded zip, and opened the Xcode project for SDKSampleApp and am not seeing any issues.  I'm able to swipe successfully.  The version on the settings page shows 1.5.1 accordingly.

**Comment by ronaldsmartin** [comment] 2015-09-14 18:49
@ppmtscory Whoops, you were right, sorry. However, after checking out the right tree (and seeing SDK Version = 1.5.1 in Settings), I'm still not detecting payment events in Simple Transaction > Swipes.

**Comment by ppmtscory** [comment] 2015-09-14 18:54
Have you removed everything on your device from the previous 1.5.2?  After doing so, are you getting prompted for microphone access now?  I went to simple transaction, purchase, selected card swipe, and then plugged in the reader.  On that page, when I plugged in the reader, I see messages saying that reader is being detected and then detected.  Once that completes, and I swipe, I then see the messages for detecting the swipe events.  Are you able to see these messages?

**Comment by ronaldsmartin** [comment] 2015-09-14 19:03
@ppmtscory:

No, I didn't uninstall and reinstall the app. I was, however, able to make some progress just now via the following:

1. Custom Card Reader Controls > Pick a fruit > Purchase
2. Custom Listen for swipes > Select "RoamAudio"

From then on, `STCardSwipeViewController` receives the appropriate payment events after trying Simple Transaction again. So far, my attempts have resulted in `ePPHTransactionType_FailedToReadCard`, but that's definitely a step forward.

Do you think it's worth uninstalling and starting from scratch?

**Comment by ppmtscory** [comment] 2015-09-14 19:04
I think so, yes.

**Comment by ronaldsmartin** [comment] 2015-09-14 19:11
I went ahead and uninstalled and reinstalled. I didn't get re-prompted for Microphone access, but that's expected because iOS keeps those privacy settings cached for at least a day. The Simple Transaction then worked as expected; I stopped getting `ePPHTransactionType_FailedToReadCard` events after removing my breakpoint on the `onPaymentEvent:` method.

Thanks for your help, @ppmtscory!

**Comment by mpavlinsky** [comment] 2015-09-14 19:12
I changed master to point at 1.5.1 for now. The issues with 1.5.2 outweigh it's value.

Thanks to both of you for your patience.

**Comment by ppmtscory** [comment] 2015-09-14 19:32
Glad it's working for you now, @ronaldsmartin.  Since this version resolves the issue posted here, I'm going to close this.  Feel free to open another issue if you run into any other problems.

**Closed by ppmtscory** 2015-09-14 19:32 UTC
